CREATE TABLE `bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`bookingNumber` varchar(50) NOT NULL,
	`serviceType` enum('hajj','umrah','hotel','flight','visa','transport','tour') NOT NULL,
	`serviceId` int NOT NULL,
	`serviceName` varchar(255),
	`status` enum('pending','confirmed','cancelled','completed','refunded') NOT NULL DEFAULT 'pending',
	`guestName` varchar(255) NOT NULL,
	`guestEmail` varchar(320),
	`guestPhone` varchar(50),
	`guestCount` int DEFAULT 1,
	`checkIn` timestamp,
	`checkOut` timestamp,
	`totalUSD` decimal(10,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`paymentStatus` enum('unpaid','partial','paid','refunded') NOT NULL DEFAULT 'unpaid',
	`stripePaymentIntentId` varchar(255),
	`notes` text,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `bookings_bookingNumber_unique` UNIQUE(`bookingNumber`)
);
--> statement-breakpoint
CREATE TABLE `flights` (
	`id` int AUTO_INCREMENT NOT NULL,
	`airline` varchar(255) NOT NULL,
	`airlineCode` varchar(10),
	`airlineLogo` text,
	`flightNumber` varchar(20) NOT NULL,
	`origin` varchar(10) NOT NULL,
	`originCity` varchar(100),
	`destination` varchar(10) NOT NULL,
	`destinationCity` varchar(100),
	`departureTime` timestamp NOT NULL,
	`arrivalTime` timestamp NOT NULL,
	`duration` int NOT NULL,
	`stops` int DEFAULT 0,
	`stopCities` json DEFAULT ('[]'),
	`cabinClass` enum('economy','business','first') NOT NULL DEFAULT 'economy',
	`priceUSD` decimal(10,2) NOT NULL,
	`seatsAvailable` int DEFAULT 50,
	`baggage` varchar(100),
	`amenities` json DEFAULT ('[]'),
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `flights_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `hajj_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`subtitle` varchar(500),
	`portalType` enum('internal','external','both') NOT NULL DEFAULT 'both',
	`category` varchar(100) NOT NULL DEFAULT 'standard',
	`imageUrl` text,
	`galleryImages` json DEFAULT ('[]'),
	`priceUSD` decimal(10,2) NOT NULL,
	`originalPriceUSD` decimal(10,2),
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`duration` int NOT NULL DEFAULT 14,
	`departureCity` varchar(100),
	`departureDate` timestamp,
	`returnDate` timestamp,
	`seatsTotal` int DEFAULT 50,
	`seatsAvailable` int DEFAULT 50,
	`hotelMakkah` varchar(255),
	`hotelMadinah` varchar(255),
	`hotelStarRating` int DEFAULT 4,
	`features` json DEFAULT ('[]'),
	`inclusions` json DEFAULT ('[]'),
	`exclusions` json DEFAULT ('[]'),
	`itinerary` json DEFAULT ('[]'),
	`isUrgent` boolean DEFAULT false,
	`isFeatured` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`badge` varchar(100),
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hajj_programs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `hotels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`city` enum('makkah','madinah','jeddah','other') NOT NULL DEFAULT 'makkah',
	`address` text,
	`distanceToHaram` decimal(6,2),
	`starRating` int DEFAULT 4,
	`imageUrl` text,
	`galleryImages` json DEFAULT ('[]'),
	`pricePerNightUSD` decimal(10,2) NOT NULL,
	`amenities` json DEFAULT ('[]'),
	`roomTypes` json DEFAULT ('[]'),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`checkInTime` varchar(10) DEFAULT '14:00',
	`checkOutTime` varchar(10) DEFAULT '12:00',
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`rating` decimal(3,1) DEFAULT '4.5',
	`reviewCount` int DEFAULT 0,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hotels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`orderNumber` varchar(50) NOT NULL,
	`status` enum('pending','confirmed','processing','shipped','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`items` json NOT NULL,
	`subtotalUSD` decimal(10,2) NOT NULL,
	`shippingUSD` decimal(10,2) DEFAULT '0',
	`taxUSD` decimal(10,2) DEFAULT '0',
	`totalUSD` decimal(10,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`stripePaymentIntentId` varchar(255),
	`shippingAddress` json,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `product_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`imageUrl` text,
	`sortOrder` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `product_categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `product_categories_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`categoryId` int,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`shortDescription` varchar(500),
	`imageUrl` text,
	`galleryImages` json DEFAULT ('[]'),
	`priceUSD` decimal(10,2) NOT NULL,
	`originalPriceUSD` decimal(10,2),
	`sku` varchar(100),
	`stock` int DEFAULT 100,
	`weight` decimal(6,2),
	`dimensions` json,
	`variants` json DEFAULT ('[]'),
	`tags` json DEFAULT ('[]'),
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`rating` decimal(3,1) DEFAULT '4.5',
	`reviewCount` int DEFAULT 0,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `site_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`key` varchar(255) NOT NULL,
	`value` text,
	`type` enum('string','number','boolean','json') NOT NULL DEFAULT 'string',
	`category` varchar(100) DEFAULT 'general',
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `site_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `site_settings_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
CREATE TABLE `tours` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`subtitle` varchar(500),
	`location` enum('makkah','madinah','taif','jeddah','other') NOT NULL DEFAULT 'makkah',
	`category` enum('religious','cultural','historical','combined') NOT NULL DEFAULT 'religious',
	`description` text,
	`imageUrl` text,
	`galleryImages` json DEFAULT ('[]'),
	`priceUSD` decimal(10,2) NOT NULL,
	`pricePerGroupUSD` decimal(10,2),
	`duration` int NOT NULL DEFAULT 4,
	`durationUnit` enum('hours','days') NOT NULL DEFAULT 'hours',
	`maxGroupSize` int DEFAULT 20,
	`minGroupSize` int DEFAULT 1,
	`language` json DEFAULT ('["Arabic","English"]'),
	`sites` json DEFAULT ('[]'),
	`itinerary` json DEFAULT ('[]'),
	`includes` json DEFAULT ('[]'),
	`guideId` int,
	`guideName` varchar(255),
	`guideImage` text,
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`rating` decimal(3,1) DEFAULT '4.8',
	`reviewCount` int DEFAULT 0,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tours_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `umrah_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`subtitle` varchar(500),
	`portalType` enum('internal','external','both') NOT NULL DEFAULT 'both',
	`category` varchar(100) NOT NULL DEFAULT 'standard',
	`imageUrl` text,
	`galleryImages` json DEFAULT ('[]'),
	`priceUSD` decimal(10,2) NOT NULL,
	`originalPriceUSD` decimal(10,2),
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`duration` int NOT NULL DEFAULT 10,
	`departureCity` varchar(100),
	`departureDate` timestamp,
	`returnDate` timestamp,
	`seatsTotal` int DEFAULT 40,
	`seatsAvailable` int DEFAULT 40,
	`hotelMakkah` varchar(255),
	`hotelMadinah` varchar(255),
	`hotelStarRating` int DEFAULT 4,
	`amenities` json DEFAULT ('[]'),
	`features` json DEFAULT ('[]'),
	`inclusions` json DEFAULT ('[]'),
	`exclusions` json DEFAULT ('[]'),
	`itinerary` json DEFAULT ('[]'),
	`isUrgent` boolean DEFAULT false,
	`isFeatured` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`badge` varchar(100),
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `umrah_programs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('vip_car','sedan','suv','van','minibus','bus') NOT NULL,
	`description` text,
	`imageUrl` text,
	`capacity` int NOT NULL,
	`pricePerTripUSD` decimal(10,2) NOT NULL,
	`pricePerDayUSD` decimal(10,2),
	`features` json DEFAULT ('[]'),
	`isAvailable` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `visa_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`visaTypeId` int NOT NULL,
	`applicantName` varchar(255) NOT NULL,
	`passportNumber` varchar(50) NOT NULL,
	`nationality` varchar(100) NOT NULL,
	`dateOfBirth` timestamp,
	`status` enum('pending','processing','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
	`documents` json DEFAULT ('[]'),
	`notes` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`processedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `visa_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `visa_types` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('umrah','hajj','tourist','transit','business','family') NOT NULL,
	`description` text,
	`imageUrl` text,
	`priceUSD` decimal(10,2) NOT NULL,
	`processingDays` int DEFAULT 5,
	`validityDays` int DEFAULT 30,
	`maxStayDays` int DEFAULT 30,
	`requirements` json DEFAULT ('[]'),
	`steps` json DEFAULT ('[]'),
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `visa_types_id` PRIMARY KEY(`id`)
);
