ALTER TABLE `flights` MODIFY COLUMN `stopCities` json;--> statement-breakpoint
ALTER TABLE `flights` MODIFY COLUMN `amenities` json;--> statement-breakpoint
ALTER TABLE `hajj_programs` MODIFY COLUMN `galleryImages` json;--> statement-breakpoint
ALTER TABLE `hajj_programs` MODIFY COLUMN `features` json;--> statement-breakpoint
ALTER TABLE `hajj_programs` MODIFY COLUMN `inclusions` json;--> statement-breakpoint
ALTER TABLE `hajj_programs` MODIFY COLUMN `exclusions` json;--> statement-breakpoint
ALTER TABLE `hajj_programs` MODIFY COLUMN `itinerary` json;--> statement-breakpoint
ALTER TABLE `hotels` MODIFY COLUMN `galleryImages` json;--> statement-breakpoint
ALTER TABLE `hotels` MODIFY COLUMN `amenities` json;--> statement-breakpoint
ALTER TABLE `hotels` MODIFY COLUMN `roomTypes` json;--> statement-breakpoint
ALTER TABLE `products` MODIFY COLUMN `galleryImages` json;--> statement-breakpoint
ALTER TABLE `products` MODIFY COLUMN `variants` json;--> statement-breakpoint
ALTER TABLE `products` MODIFY COLUMN `tags` json;--> statement-breakpoint
ALTER TABLE `tours` MODIFY COLUMN `galleryImages` json;--> statement-breakpoint
ALTER TABLE `tours` MODIFY COLUMN `language` json;--> statement-breakpoint
ALTER TABLE `tours` MODIFY COLUMN `sites` json;--> statement-breakpoint
ALTER TABLE `tours` MODIFY COLUMN `itinerary` json;--> statement-breakpoint
ALTER TABLE `tours` MODIFY COLUMN `includes` json;--> statement-breakpoint
ALTER TABLE `umrah_programs` MODIFY COLUMN `galleryImages` json;--> statement-breakpoint
ALTER TABLE `umrah_programs` MODIFY COLUMN `amenities` json;--> statement-breakpoint
ALTER TABLE `umrah_programs` MODIFY COLUMN `features` json;--> statement-breakpoint
ALTER TABLE `umrah_programs` MODIFY COLUMN `inclusions` json;--> statement-breakpoint
ALTER TABLE `umrah_programs` MODIFY COLUMN `exclusions` json;--> statement-breakpoint
ALTER TABLE `umrah_programs` MODIFY COLUMN `itinerary` json;--> statement-breakpoint
ALTER TABLE `vehicles` MODIFY COLUMN `features` json;--> statement-breakpoint
ALTER TABLE `visa_applications` MODIFY COLUMN `documents` json;--> statement-breakpoint
ALTER TABLE `visa_types` MODIFY COLUMN `requirements` json;--> statement-breakpoint
ALTER TABLE `visa_types` MODIFY COLUMN `steps` json;