CREATE TABLE `dynamic_pricing_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('seasonal','early_bird','last_minute','group','occupancy') NOT NULL,
	`serviceType` enum('hajj','umrah','hotel','flight','all') NOT NULL DEFAULT 'all',
	`discountPercent` decimal(5,2) NOT NULL,
	`minDaysAhead` int,
	`maxDaysAhead` int,
	`minGroupSize` int,
	`minOccupancyPercent` decimal(5,2),
	`startDate` timestamp,
	`endDate` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`priority` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dynamic_pricing_rules_id` PRIMARY KEY(`id`),
	CONSTRAINT `dynamic_pricing_rules_ruleId_unique` UNIQUE(`ruleId`)
);
--> statement-breakpoint
CREATE TABLE `passport_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`bookingId` int,
	`imageUrl` text,
	`passportNumber` varchar(50),
	`fullName` varchar(255),
	`nationality` varchar(100),
	`dateOfBirth` varchar(20),
	`expiryDate` varchar(20),
	`gender` varchar(10),
	`placeOfBirth` varchar(100),
	`mrz` text,
	`confidence` decimal(5,2),
	`rawOcrData` json,
	`status` enum('pending','verified','rejected') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `passport_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `train_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingRef` varchar(50) NOT NULL,
	`userId` int,
	`umrahProgramId` int,
	`passengerName` varchar(255) NOT NULL,
	`passengerEmail` varchar(320),
	`passengerPhone` varchar(50),
	`passportNumber` varchar(50),
	`fromStation` enum('makkah','jeddah','madinah','king_abdulaziz') NOT NULL,
	`toStation` enum('makkah','jeddah','madinah','king_abdulaziz') NOT NULL,
	`travelDate` timestamp NOT NULL,
	`returnDate` timestamp,
	`trainClass` enum('economy','business','vip') NOT NULL DEFAULT 'economy',
	`passengers` int NOT NULL DEFAULT 1,
	`priceUSD` decimal(10,2) NOT NULL,
	`status` enum('pending','confirmed','cancelled') NOT NULL DEFAULT 'pending',
	`seatNumbers` json,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `train_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `train_bookings_bookingRef_unique` UNIQUE(`bookingRef`)
);
