CREATE TABLE `hajj_companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` varchar(50) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`licenseNumber` varchar(100),
	`logoUrl` text,
	`coverImageUrl` text,
	`galleryImages` json,
	`city` varchar(100),
	`address` text,
	`phone` varchar(50),
	`whatsapp` varchar(50),
	`email` varchar(255),
	`website` varchar(255),
	`description` text,
	`descriptionEn` text,
	`nusukProfileUrl` text,
	`specializations` json,
	`yearsExperience` int DEFAULT 0,
	`totalPilgrims` int DEFAULT 0,
	`averageRating` decimal(3,2) DEFAULT '0.00',
	`totalReviews` int DEFAULT 0,
	`isVerified` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hajj_companies_id` PRIMARY KEY(`id`),
	CONSTRAINT `hajj_companies_companyId_unique` UNIQUE(`companyId`)
);
--> statement-breakpoint
CREATE TABLE `hajj_company_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` varchar(50) NOT NULL,
	`userId` int,
	`reviewerName` varchar(255) NOT NULL,
	`reviewerEmail` varchar(255),
	`bookingReference` varchar(100),
	`isVerifiedPilgrim` boolean DEFAULT false,
	`rating` int NOT NULL,
	`ratingService` int,
	`ratingAccommodation` int,
	`ratingTransport` int,
	`ratingFood` int,
	`reviewText` text,
	`hajjYear` int,
	`isApproved` boolean DEFAULT false,
	`isHidden` boolean DEFAULT false,
	`adminNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `hajj_company_reviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `hajj_domestic_notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`notifId` varchar(50) NOT NULL,
	`titleAr` varchar(500) NOT NULL,
	`titleEn` varchar(500),
	`contentAr` text NOT NULL,
	`contentEn` text,
	`category` enum('news','alert','announcement','article','update') NOT NULL DEFAULT 'news',
	`imageUrl` text,
	`sourceUrl` text,
	`isUrgent` boolean DEFAULT false,
	`isPinned` boolean DEFAULT false,
	`isPublished` boolean DEFAULT true,
	`sentViaEmail` boolean DEFAULT false,
	`sentViaWhatsapp` boolean DEFAULT false,
	`emailSentAt` timestamp,
	`whatsappSentAt` timestamp,
	`recipientCount` int DEFAULT 0,
	`publishedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hajj_domestic_notifications_id` PRIMARY KEY(`id`),
	CONSTRAINT `hajj_domestic_notifications_notifId_unique` UNIQUE(`notifId`)
);
--> statement-breakpoint
CREATE TABLE `hajj_international_packages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageId` varchar(50) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`titleEn` varchar(255),
	`companyName` varchar(255) NOT NULL,
	`companyNameAr` varchar(255),
	`companyLogoUrl` text,
	`countryCode` varchar(10) NOT NULL,
	`countryAr` varchar(100) NOT NULL,
	`countryEn` varchar(100) NOT NULL,
	`cityAr` varchar(100),
	`cityEn` varchar(100),
	`imageUrl` text,
	`galleryImages` json,
	`priceUSD` decimal(10,2) NOT NULL,
	`priceSAR` decimal(10,2),
	`localCurrency` varchar(10),
	`localPrice` decimal(12,2),
	`duration` int DEFAULT 21,
	`departureDate` timestamp,
	`returnDate` timestamp,
	`seatsTotal` int DEFAULT 50,
	`seatsAvailable` int DEFAULT 50,
	`hotelMakkah` varchar(255),
	`hotelMadinah` varchar(255),
	`hotelStarRating` int DEFAULT 4,
	`features` json,
	`inclusions` json,
	`contactPhone` varchar(50),
	`contactWhatsapp` varchar(50),
	`contactEmail` varchar(255),
	`category` varchar(100) DEFAULT 'standard',
	`isUrgent` boolean DEFAULT false,
	`isFeatured` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hajj_international_packages_id` PRIMARY KEY(`id`),
	CONSTRAINT `hajj_international_packages_packageId_unique` UNIQUE(`packageId`)
);
--> statement-breakpoint
CREATE TABLE `notification_subscribers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255),
	`email` varchar(255),
	`whatsapp` varchar(50),
	`subscriptionType` enum('email','whatsapp','both') NOT NULL DEFAULT 'email',
	`topics` json,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notification_subscribers_id` PRIMARY KEY(`id`)
);
