CREATE TABLE `flexible_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` varchar(36) NOT NULL,
	`serviceType` enum('hajj','umrah','hotel','flight','visa','transport','tour','other') NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerPhone` varchar(100) NOT NULL,
	`customerEmail` varchar(255),
	`customerWhatsapp` varchar(100),
	`nationality` varchar(100),
	`departureCity` varchar(255),
	`destination` varchar(255),
	`travelDate` varchar(50),
	`returnDate` varchar(50),
	`adults` int DEFAULT 1,
	`children` int DEFAULT 0,
	`budgetMin` decimal(10,2),
	`budgetMax` decimal(10,2),
	`currency` varchar(10) DEFAULT 'USD',
	`hotelStars` int,
	`specialRequirements` text,
	`notes` text,
	`status` enum('new','reviewing','quoted','confirmed','cancelled') NOT NULL DEFAULT 'new',
	`adminNotes` text,
	`quotedPrice` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `flexible_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `flexible_requests_requestId_unique` UNIQUE(`requestId`)
);
