CREATE TABLE `provider_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingRef` varchar(36) NOT NULL,
	`programId` int NOT NULL,
	`providerId` int NOT NULL,
	`customerId` int,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(255),
	`customerPhone` varchar(100),
	`customerWhatsapp` varchar(100),
	`adults` int DEFAULT 1,
	`children` int DEFAULT 0,
	`totalUSD` decimal(10,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`status` enum('pending','confirmed','processing','completed','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`notes` text,
	`providerNotes` text,
	`paymentStatus` enum('unpaid','partial','paid','refunded') NOT NULL DEFAULT 'unpaid',
	`paidAmount` decimal(10,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `provider_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `provider_bookings_bookingRef_unique` UNIQUE(`bookingRef`)
);
--> statement-breakpoint
CREATE TABLE `provider_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`companyNameAr` varchar(255),
	`licenseNumber` varchar(100),
	`licenseExpiry` varchar(50),
	`contactPhone` varchar(100),
	`contactWhatsapp` varchar(100),
	`contactEmail` varchar(255),
	`website` varchar(500),
	`logoUrl` text,
	`coverUrl` text,
	`description` text,
	`descriptionAr` text,
	`address` text,
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'SA',
	`serviceTypes` json DEFAULT ('[]'),
	`rating` decimal(3,1) DEFAULT '0.0',
	`reviewCount` int DEFAULT 0,
	`totalBookings` int DEFAULT 0,
	`isVerified` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`status` enum('pending','approved','suspended') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `provider_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `provider_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `provider_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`providerId` int NOT NULL,
	`programType` enum('hajj','umrah','hotel','flight','visa','transport','tour','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`titleAr` varchar(255),
	`description` text,
	`descriptionAr` text,
	`imageUrl` text,
	`galleryImages` json DEFAULT ('[]'),
	`priceUSD` decimal(10,2) NOT NULL,
	`originalPriceUSD` decimal(10,2),
	`currency` varchar(10) DEFAULT 'USD',
	`duration` varchar(100),
	`capacity` int DEFAULT 20,
	`availableSlots` int DEFAULT 20,
	`departureCity` varchar(100),
	`destination` varchar(100) DEFAULT 'Makkah',
	`startDate` varchar(50),
	`endDate` varchar(50),
	`features` json DEFAULT ('[]'),
	`inclusions` json DEFAULT ('[]'),
	`exclusions` json DEFAULT ('[]'),
	`customFields` json DEFAULT ('[]'),
	`tags` json DEFAULT ('[]'),
	`isActive` boolean DEFAULT true,
	`isFeatured` boolean DEFAULT false,
	`rating` decimal(3,1) DEFAULT '0.0',
	`reviewCount` int DEFAULT 0,
	`totalBookings` int DEFAULT 0,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `provider_programs_id` PRIMARY KEY(`id`)
);
