import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

export type Language = "en" | "ar" | "ur" | "tr" | "id" | "fr";

export interface LanguageConfig {
  code: Language;
  name: string;
  nativeName: string;
  dir: "ltr" | "rtl";
  flag: string;
}

export const LANGUAGES: LanguageConfig[] = [
  { code: "en", name: "English", nativeName: "English", dir: "ltr", flag: "🇬🇧" },
  { code: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "ur", name: "Urdu", nativeName: "اردو", dir: "rtl", flag: "🇵🇰" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", dir: "ltr", flag: "🇹🇷" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", dir: "ltr", flag: "🇮🇩" },
  { code: "fr", name: "French", nativeName: "Français", dir: "ltr", flag: "🇫🇷" },
];

// ─── Translation Strings ──────────────────────────────────────────────────────

export type TranslationKey =
  | "nav.hajj" | "nav.umrah" | "nav.hotels" | "nav.flights" | "nav.visa"
  | "nav.transport" | "nav.tours" | "nav.store" | "nav.admin" | "nav.login" | "nav.logout" | "nav.flexibleRequest" | "nav.media" | "nav.news"
  | "home.hero.title1" | "home.hero.title2" | "home.hero.subtitle" | "home.hero.search"
  | "home.hero.cta.hajj" | "home.hero.cta.umrah"
  | "home.services.title" | "home.services.subtitle"
  | "home.featured.title" | "home.featured.subtitle"
  | "common.bookNow" | "common.learnMore" | "common.viewAll" | "common.search"
  | "common.filter" | "common.sort" | "common.price" | "common.duration"
  | "common.featured" | "common.urgent" | "common.available" | "common.soldOut"
  | "common.from" | "common.perPerson" | "common.perNight" | "common.loading"
  | "common.noResults" | "common.days" | "common.nights" | "common.persons"
  | "common.submit" | "common.cancel" | "common.save" | "common.delete" | "common.edit"
  | "common.add" | "common.close" | "common.back" | "common.next" | "common.confirm"
  | "hajj.title" | "hajj.subtitle" | "hajj.internal" | "hajj.external"
  | "hajj.filter.all" | "hajj.filter.economy" | "hajj.filter.standard" | "hajj.filter.premium" | "hajj.filter.vip"
  | "umrah.title" | "umrah.subtitle" | "umrah.internal" | "umrah.external"
  | "hotels.title" | "hotels.subtitle" | "hotels.search.destination" | "hotels.search.checkin"
  | "hotels.search.checkout" | "hotels.search.guests" | "hotels.filter.stars"
  | "hotels.filter.price" | "hotels.filter.proximity" | "hotels.proximity.haram"
  | "flights.title" | "flights.subtitle" | "flights.from" | "flights.to"
  | "flights.depart" | "flights.return" | "flights.passengers" | "flights.cabin"
  | "flights.economy" | "flights.business" | "flights.first"
  | "visa.title" | "visa.subtitle" | "visa.apply" | "visa.track" | "visa.status"
  | "visa.umrah" | "visa.hajj" | "visa.tourist" | "visa.transit"
  | "transport.title" | "transport.subtitle" | "transport.from" | "transport.to"
  | "transport.date" | "transport.passengers" | "transport.vip" | "transport.van" | "transport.bus"
  | "tours.title" | "tours.subtitle" | "tours.makkah" | "tours.madinah"
  | "tours.religious" | "tours.cultural" | "tours.historical"
  | "store.title" | "store.subtitle" | "store.cart" | "store.checkout"
  | "store.addToCart" | "store.buyNow" | "store.inStock" | "store.outOfStock"
  | "admin.title" | "admin.dashboard" | "admin.localization" | "admin.pricing"
  | "admin.users" | "admin.bookings" | "admin.orders" | "admin.settings"
  | "lang.select" | "currency.select" | "bismillah"
  | "common.person" | "common.explore"
  | "badge.limited" | "badge.featured"
  | "home.hero.badge" | "home.hero.title" | "home.hero.titleHighlight" | "home.hero.searchPlaceholder"
  | "home.services.badge" | "home.services.hajj" | "home.services.umrah" | "home.services.hotels"
  | "home.services.flights" | "home.services.visa" | "home.services.transport"
  | "home.services.tours" | "home.services.store"
  | "home.stats.pilgrims" | "home.stats.years" | "home.stats.satisfaction" | "home.stats.support"
  | "home.hajj.badge" | "home.hajj.title"
  | "home.umrah.badge" | "home.umrah.title"
  | "home.why.badge" | "home.why.title" | "home.why.titleHighlight" | "home.why.subtitle" | "home.why.cta"
  | "home.testimonials.badge" | "home.testimonials.title" | "home.testimonials.t1" | "home.testimonials.t2" | "home.testimonials.t3"
  | "home.cta.title" | "home.cta.subtitle" | "home.cta.hajjBtn" | "home.cta.umrahBtn"
  | "home.features.licensed" | "home.features.multilingual" | "home.features.transparent"
  | "home.features.payment" | "home.features.realtime" | "home.features.insurance"
  | "common.hide" | "common.view"
  | "visa.applyNow" | "visa.entry" | "visa.processing" | "visa.processingFee"
  | "visa.requirements" | "visa.validity"
  | "footer.tagline" | "footer.quickLinks" | "footer.services" | "footer.contact"
  | "footer.rights" | "footer.privacy" | "footer.terms"
  | "common.allRatings" | "common.allPrices" | "common.perRoom"
  | "hotels.noResults" | "hotels.mapView" | "hotels.listView"
  | "transport.private" | "transport.shared" | "transport.pickup" | "transport.dropoff"
  | "tours.duration" | "tours.groupSize" | "tours.guide" | "tours.bookTour"
  | "store.quantity" | "store.total" | "store.emptyCart" | "store.continueShopping"
  | "store.placeOrder" | "store.orderSuccess"
  | "admin.add" | "admin.edit" | "admin.delete" | "admin.save" | "admin.cancel"
  | "admin.hajj" | "admin.umrah" | "admin.hotels" | "admin.flights" | "admin.visa"
  | "admin.transport" | "admin.tours" | "admin.store" | "admin.analytics"
  | "common.internalPortal" | "common.externalPortal"
  | "hajj.nights" | "hajj.includes" | "hajj.economy" | "hajj.premium" | "hajj.vip"
  | "umrah.nights" | "umrah.includes" | "umrah.economy" | "umrah.premium" | "umrah.vip";

type Translations = Record<TranslationKey, string>;

const translations: Record<Language, Translations> = {
  en: {
    "nav.hajj": "Hajj Programs",
    "nav.umrah": "Umrah Programs",
    "nav.hotels": "Hotels",
    "nav.flights": "Flights",
    "nav.visa": "Visa",
    "nav.transport": "Transport",
    "nav.tours": "Ziyarat Tours",
    "nav.store": "Store",
    "nav.admin": "Admin",
    "nav.login": "Sign In",
    "nav.logout": "Sign Out",
    "nav.flexibleRequest": "Custom Request",
    "nav.media": "Media Center",
    "nav.news": "News",
    "home.hero.title1": "Your Sacred Journey",
    "home.hero.title2": "Begins Here",
    "home.hero.subtitle": "Experience the most blessed journey of your life with Go Umrah — your trusted partner for Hajj, Umrah, and all pilgrimage services.",
    "home.hero.search": "Search Hajj, Umrah, Hotels...",
    "home.hero.cta.hajj": "Hajj Programs",
    "home.hero.cta.umrah": "Umrah Packages",
    "home.services.title": "Our Complete Services",
    "home.services.subtitle": "Everything you need for your sacred pilgrimage, in one place.",
    "home.featured.title": "Featured Programs",
    "home.featured.subtitle": "Handpicked packages for an exceptional spiritual experience.",
    "common.bookNow": "Book Now",
    "common.learnMore": "Learn More",
    "common.viewAll": "View All",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.price": "Price",
    "common.duration": "Duration",
    "common.featured": "Featured",
    "common.urgent": "Limited Seats",
    "common.available": "Available",
    "common.soldOut": "Sold Out",
    "common.from": "From",
    "common.perPerson": "per person",
    "common.perNight": "per night",
    "common.loading": "Loading...",
    "common.noResults": "No results found.",
    "common.days": "days",
    "common.nights": "nights",
    "common.persons": "persons",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.confirm": "Confirm",
    "hajj.title": "Hajj Programs",
    "hajj.subtitle": "Complete Hajj packages with premium accommodations and guided services.",
    "hajj.internal": "Internal Programs",
    "hajj.external": "External Programs",
    "hajj.filter.all": "All Programs",
    "hajj.filter.economy": "Economy",
    "hajj.filter.standard": "Standard",
    "hajj.filter.premium": "Premium",
    "hajj.filter.vip": "VIP",
    "umrah.title": "Umrah Programs",
    "umrah.subtitle": "Spiritual Umrah packages tailored for every pilgrim.",
    "umrah.internal": "Internal Programs",
    "umrah.external": "External Programs",
    "hotels.title": "Hotel Booking",
    "hotels.subtitle": "Premium hotels near Al-Masjid Al-Haram and Al-Masjid An-Nabawi.",
    "hotels.search.destination": "Destination",
    "hotels.search.checkin": "Check-in",
    "hotels.search.checkout": "Check-out",
    "hotels.search.guests": "Guests",
    "hotels.filter.stars": "Star Rating",
    "hotels.filter.price": "Price Range",
    "hotels.filter.proximity": "Proximity to Haram",
    "hotels.proximity.haram": "Distance to Haram",
    "flights.title": "Flight Booking",
    "flights.subtitle": "Direct and connecting flights to Jeddah & Madinah.",
    "flights.from": "From",
    "flights.to": "To",
    "flights.depart": "Departure",
    "flights.return": "Return",
    "flights.passengers": "Passengers",
    "flights.cabin": "Cabin Class",
    "flights.economy": "Economy",
    "flights.business": "Business",
    "flights.first": "First Class",
    "visa.title": "Visa Services",
    "visa.subtitle": "Fast and reliable visa processing for all pilgrims.",
    "visa.apply": "Apply Now",
    "visa.track": "Track Application",
    "visa.status": "Status",
    "visa.umrah": "Umrah Visa",
    "visa.hajj": "Hajj Visa",
    "visa.tourist": "Tourist Visa",
    "visa.transit": "Transit Visa",
    "transport.title": "Transportation",
    "transport.subtitle": "VIP private transfers and group transport across the Holy Cities.",
    "transport.from": "Pickup Location",
    "transport.to": "Drop-off Location",
    "transport.date": "Travel Date",
    "transport.passengers": "Passengers",
    "transport.vip": "VIP Car",
    "transport.van": "Van",
    "transport.bus": "Bus",
    "tours.title": "Ziyarat Tours",
    "tours.subtitle": "Guided religious and cultural tours in Makkah and Madinah.",
    "tours.makkah": "Makkah Tours",
    "tours.madinah": "Madinah Tours",
    "tours.religious": "Religious Sites",
    "tours.cultural": "Cultural Tours",
    "tours.historical": "Historical Sites",
    "store.title": "Pilgrimage Store",
    "store.subtitle": "Premium essentials for your sacred journey.",
    "store.cart": "Cart",
    "store.checkout": "Checkout",
    "store.addToCart": "Add to Cart",
    "store.buyNow": "Buy Now",
    "store.inStock": "In Stock",
    "store.outOfStock": "Out of Stock",
    "admin.title": "Command Center",
    "admin.dashboard": "Dashboard",
    "admin.localization": "Localization & Pricing",
    "admin.pricing": "Pricing Management",
    "admin.users": "Users",
    "admin.bookings": "Bookings",
    "admin.orders": "Orders",
    "admin.settings": "Settings",
    "lang.select": "Language",
    "currency.select": "Currency",
    "bismillah": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "common.person": "person",
    "common.explore": "Explore",
    "badge.limited": "Limited Seats",
    "badge.featured": "Featured",
    "home.hero.badge": "Trusted by 50,000+ Pilgrims",
    "home.hero.title": "Your Sacred Journey",
    "home.hero.titleHighlight": "Begins Here",
    "home.hero.searchPlaceholder": "Search Hajj, Umrah, Hotels...",
    "home.services.badge": "Our Services",
    "home.services.hajj": "Complete Hajj packages with premium accommodations and expert guides.",
    "home.services.umrah": "Spiritual Umrah packages tailored for every pilgrim.",
    "home.services.hotels": "Premium hotels near Al-Masjid Al-Haram and Al-Masjid An-Nabawi.",
    "home.services.flights": "Direct and connecting flights to Jeddah & Madinah.",
    "home.services.visa": "Fast and reliable visa processing for all pilgrims.",
    "home.services.transport": "VIP private transfers and group transport across the Holy Cities.",
    "home.services.tours": "Guided religious and cultural tours in Makkah and Madinah.",
    "home.services.store": "Premium essentials for your sacred pilgrimage journey.",
    "home.stats.pilgrims": "Happy Pilgrims",
    "home.stats.years": "Years Experience",
    "home.stats.satisfaction": "Satisfaction Rate",
    "home.stats.support": "Support Available",
    "home.hajj.badge": "Hajj Programs",
    "home.hajj.title": "Featured Hajj Packages",
    "home.umrah.badge": "Umrah Programs",
    "home.umrah.title": "Featured Umrah Packages",
    "home.why.badge": "Why Go Umrah",
    "home.why.title": "Your Journey, Our",
    "home.why.titleHighlight": "Commitment",
    "home.why.subtitle": "With over 15 years of experience, Go Umrah has guided more than 50,000 pilgrims on their sacred journeys.",
    "home.why.cta": "Start Your Journey",
    "home.testimonials.badge": "Testimonials",
    "home.testimonials.title": "What Our Pilgrims Say",
    "home.testimonials.t1": "Go Umrah made our Hajj experience truly unforgettable. The attention to detail, the guidance, and the support throughout the journey was exceptional.",
    "home.testimonials.t2": "We traveled as a family of 6 for Umrah and everything was perfectly arranged. The hotel was steps from the Haram and the team was available 24/7.",
    "home.testimonials.t3": "The visa processing was fast and hassle-free. The Ziyarat tours were incredibly informative and spiritually enriching.",
    "home.cta.title": "Ready to Begin Your Sacred Journey?",
    "home.cta.subtitle": "Join thousands of pilgrims who have trusted Go Umrah for their Hajj and Umrah experiences.",
    "home.cta.hajjBtn": "Book Hajj Package",
    "home.cta.umrahBtn": "Book Umrah Package",
    "home.features.licensed": "Government Licensed & Certified",
    "home.features.multilingual": "Multilingual Support (6 Languages)",
    "home.features.transparent": "Transparent Pricing — No Hidden Fees",
    "home.features.payment": "Flexible Payment Plans Available",
    "home.features.realtime": "Real-time Booking Confirmation",
    "home.features.insurance": "Full Travel Insurance Included",
    "common.hide": "Hide",
    "common.view": "View",
    "visa.applyNow": "Apply Now",
    "visa.entry": "Entry",
    "visa.processing": "Processing",
    "visa.processingFee": "Processing Fee",
    "visa.requirements": "Requirements",
    "visa.validity": "Validity",
    "footer.tagline": "Your trusted partner for Hajj & Umrah journeys",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.contact": "Contact Us",
    "footer.rights": "All rights reserved",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "common.allRatings": "All Ratings",
    "common.allPrices": "All Prices",
    "common.perRoom": "per room",
    "hotels.noResults": "No hotels found",
    "hotels.mapView": "Map View",
    "hotels.listView": "List View",
    "transport.private": "Private",
    "transport.shared": "Shared",
    "transport.pickup": "Pickup Location",
    "transport.dropoff": "Drop-off Location",
    "tours.duration": "Duration",
    "tours.groupSize": "Group Size",
    "tours.guide": "Guide",
    "tours.bookTour": "Book Tour",
    "store.quantity": "Quantity",
    "store.total": "Total",
    "store.emptyCart": "Your cart is empty",
    "store.continueShopping": "Continue Shopping",
    "store.placeOrder": "Place Order",
    "store.orderSuccess": "Order placed successfully!",
    "admin.add": "Add New",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save Changes",
    "admin.cancel": "Cancel",
    "admin.hajj": "Hajj Programs",
    "admin.umrah": "Umrah Programs",
    "admin.hotels": "Hotels",
    "admin.flights": "Flights",
    "admin.visa": "Visa Types",
    "admin.transport": "Transport",
    "admin.tours": "Tours",
    "admin.store": "Store",
    "admin.analytics": "Analytics",
    "common.internalPortal": "Internal Portal",
    "common.externalPortal": "External Portal",
    "hajj.nights": "Nights",
    "hajj.includes": "Includes",
    "hajj.economy": "Economy",
    "hajj.premium": "Premium",
    "hajj.vip": "VIP",
    "umrah.nights": "Nights",
    "umrah.includes": "Includes",
    "umrah.economy": "Economy",
    "umrah.premium": "Premium",
    "umrah.vip": "VIP",
  },
  ar: {
    "nav.hajj": "برامج الحج",
    "nav.umrah": "برامج العمرة",
    "nav.hotels": "الفنادق",
    "nav.flights": "الرحلات",
    "nav.visa": "التأشيرة",
    "nav.transport": "المواصلات",
    "nav.tours": "جولات الزيارة",
    "nav.store": "المتجر",
    "nav.admin": "لوحة التحكم",
    "nav.login": "تسجيل الدخول",
    "nav.logout": "تسجيل الخروج",
    "nav.flexibleRequest": "طلب مرن",
    "nav.media": "المركز الإعلامي",
    "nav.news": "الأخبار",
    "home.hero.title1": "رحلتك المقدسة",
    "home.hero.title2": "تبدأ هنا",
    "home.hero.subtitle": "اختبر أعظم رحلة في حياتك مع جو عمرة — شريكك الموثوق للحج والعمرة وجميع خدمات الحج.",
    "home.hero.search": "ابحث عن الحج، العمرة، الفنادق...",
    "home.hero.cta.hajj": "برامج الحج",
    "home.hero.cta.umrah": "باقات العمرة",
    "home.services.title": "خدماتنا الشاملة",
    "home.services.subtitle": "كل ما تحتاجه لرحلتك المقدسة في مكان واحد.",
    "home.featured.title": "البرامج المميزة",
    "home.featured.subtitle": "باقات مختارة بعناية لتجربة روحية استثنائية.",
    "common.bookNow": "احجز الآن",
    "common.learnMore": "اعرف المزيد",
    "common.viewAll": "عرض الكل",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.price": "السعر",
    "common.duration": "المدة",
    "common.featured": "مميز",
    "common.urgent": "مقاعد محدودة",
    "common.available": "متاح",
    "common.soldOut": "نفذت الكمية",
    "common.from": "من",
    "common.perPerson": "للشخص",
    "common.perNight": "في الليلة",
    "common.loading": "جاري التحميل...",
    "common.noResults": "لا توجد نتائج.",
    "common.days": "أيام",
    "common.nights": "ليالٍ",
    "common.persons": "أشخاص",
    "common.submit": "إرسال",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.add": "إضافة",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.confirm": "تأكيد",
    "hajj.title": "برامج الحج",
    "hajj.subtitle": "باقات حج متكاملة مع إقامة فاخرة وخدمات إرشادية.",
    "hajj.internal": "البرامج الداخلية",
    "hajj.external": "البرامج الخارجية",
    "hajj.filter.all": "جميع البرامج",
    "hajj.filter.economy": "اقتصادي",
    "hajj.filter.standard": "قياسي",
    "hajj.filter.premium": "مميز",
    "hajj.filter.vip": "VIP",
    "umrah.title": "برامج العمرة",
    "umrah.subtitle": "باقات عمرة روحية مصممة لكل حاج.",
    "umrah.internal": "البرامج الداخلية",
    "umrah.external": "البرامج الخارجية",
    "hotels.title": "حجز الفنادق",
    "hotels.subtitle": "فنادق فاخرة قريبة من المسجد الحرام والمسجد النبوي.",
    "hotels.search.destination": "الوجهة",
    "hotels.search.checkin": "تسجيل الوصول",
    "hotels.search.checkout": "تسجيل المغادرة",
    "hotels.search.guests": "الضيوف",
    "hotels.filter.stars": "تصنيف النجوم",
    "hotels.filter.price": "نطاق السعر",
    "hotels.filter.proximity": "القرب من الحرم",
    "hotels.proximity.haram": "المسافة من الحرم",
    "flights.title": "حجز الرحلات",
    "flights.subtitle": "رحلات مباشرة وعبر محطات إلى جدة والمدينة.",
    "flights.from": "من",
    "flights.to": "إلى",
    "flights.depart": "المغادرة",
    "flights.return": "العودة",
    "flights.passengers": "المسافرون",
    "flights.cabin": "درجة الكابينة",
    "flights.economy": "اقتصادية",
    "flights.business": "رجال أعمال",
    "flights.first": "الدرجة الأولى",
    "visa.title": "خدمات التأشيرة",
    "visa.subtitle": "معالجة تأشيرة سريعة وموثوقة لجميع الحجاج.",
    "visa.apply": "تقدم الآن",
    "visa.track": "تتبع الطلب",
    "visa.status": "الحالة",
    "visa.umrah": "تأشيرة العمرة",
    "visa.hajj": "تأشيرة الحج",
    "visa.tourist": "تأشيرة سياحية",
    "visa.transit": "تأشيرة عبور",
    "transport.title": "خدمات النقل",
    "transport.subtitle": "نقل خاص VIP ونقل جماعي عبر المدن المقدسة.",
    "transport.from": "موقع الاستلام",
    "transport.to": "موقع التوصيل",
    "transport.date": "تاريخ السفر",
    "transport.passengers": "الركاب",
    "transport.vip": "سيارة VIP",
    "transport.van": "فان",
    "transport.bus": "حافلة",
    "tours.title": "جولات الزيارة",
    "tours.subtitle": "جولات دينية وثقافية إرشادية في مكة المكرمة والمدينة المنورة.",
    "tours.makkah": "جولات مكة",
    "tours.madinah": "جولات المدينة",
    "tours.religious": "المواقع الدينية",
    "tours.cultural": "الجولات الثقافية",
    "tours.historical": "المواقع التاريخية",
    "store.title": "متجر الحج",
    "store.subtitle": "مستلزمات فاخرة لرحلتك المقدسة.",
    "store.cart": "السلة",
    "store.checkout": "الدفع",
    "store.addToCart": "أضف إلى السلة",
    "store.buyNow": "اشتر الآن",
    "store.inStock": "متوفر",
    "store.outOfStock": "نفذت الكمية",
    "admin.title": "مركز التحكم",
    "admin.dashboard": "لوحة البيانات",
    "admin.localization": "الترجمة والتسعير",
    "admin.pricing": "إدارة الأسعار",
    "admin.users": "المستخدمون",
    "admin.bookings": "الحجوزات",
    "admin.orders": "الطلبات",
    "admin.settings": "الإعدادات",
    "lang.select": "اللغة",
    "currency.select": "العملة",
    "bismillah": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "common.person": "شخص",
    "common.explore": "استكشف",
    "badge.limited": "مقاعد محدودة",
    "badge.featured": "مميز",
    "home.hero.badge": "موثوق به من قبل أكثر من 50,000 حاج",
    "home.hero.title": "رحلتك المقدسة",
    "home.hero.titleHighlight": "تبدأ هنا",
    "home.hero.searchPlaceholder": "ابحث عن الحج، العمرة، الفنادق...",
    "home.services.badge": "خدماتنا",
    "home.services.hajj": "باقات حج متكاملة مع إقامة فاخرة ومرشدين خبراء.",
    "home.services.umrah": "باقات عمرة روحية مصممة لكل حاج.",
    "home.services.hotels": "فنادق فاخرة قريبة من المسجد الحرام والمسجد النبوي.",
    "home.services.flights": "رحلات مباشرة وعبر محطات إلى جدة والمدينة.",
    "home.services.visa": "معالجة تأشيرة سريعة وموثوقة لجميع الحجاج.",
    "home.services.transport": "نقل خاص VIP ونقل جماعي عبر المدن المقدسة.",
    "home.services.tours": "جولات دينية وثقافية إرشادية في مكة والمدينة.",
    "home.services.store": "مستلزمات فاخرة لرحلتك المقدسة.",
    "home.stats.pilgrims": "حاج سعيد",
    "home.stats.years": "سنوات خبرة",
    "home.stats.satisfaction": "معدل الرضا",
    "home.stats.support": "دعم متاح",
    "home.hajj.badge": "برامج الحج",
    "home.hajj.title": "باقات الحج المميزة",
    "home.umrah.badge": "برامج العمرة",
    "home.umrah.title": "باقات العمرة المميزة",
    "home.why.badge": "لماذا جو عمرة",
    "home.why.title": "رحلتك، التزامنا",
    "home.why.titleHighlight": "الراسخ",
    "home.why.subtitle": "بخبرة تزيد عن 15 عامًا، أرشد جو عمرة أكثر من 50,000 حاج في رحلاتهم المقدسة.",
    "home.why.cta": "ابدأ رحلتك",
    "home.testimonials.badge": "شهادات ضيوف الرحمن",
    "home.testimonials.title": "تقييمات حقيقة لعملاء جو عمرة",
    "home.testimonials.t1": "جعل جو عمرة تجربة حجنا لا تُنسى حقًا. الاهتمام بالتفاصيل والإرشاد والدعم طوال الرحلة كان استثنائيًا.",
    "home.testimonials.t2": "سافرنا كعائلة مكونة من 6 أفراد للعمرة وتم ترتيب كل شيء بشكل مثالي. كان الفندق على بعد خطوات من الحرم والفريق كان متاحًا على مدار الساعة.",
    "home.testimonials.t3": "كانت معالجة التأشيرة سريعة وخالية من المتاعب. كانت جولات الزيارة مفيدة بشكل لا يصدق وغنية روحيًا.",
    "home.cta.title": "هل أنت مستعد لبدء رحلتك المقدسة؟",
    "home.cta.subtitle": "انضم إلى آلاف الحجاج الذين وثقوا بجو عمرة لتجارب الحج والعمرة.",
    "home.cta.hajjBtn": "احجز باقة الحج",
    "home.cta.umrahBtn": "احجز باقة العمرة",
    "home.features.licensed": "مرخص ومعتمد حكوميًا",
    "home.features.multilingual": "دعم متعدد اللغات (6 لغات)",
    "home.features.transparent": "أسعار شفافة — بدون رسوم خفية",
    "home.features.payment": "خطط دفع مرنة متاحة",
    "home.features.realtime": "تأكيد الحجز الفوري",
    "home.features.insurance": "تأمين سفر شامل مدرج",
    "common.hide": "إخفاء",
    "common.view": "عرض",
    "visa.applyNow": "تقدم الآن",
    "visa.entry": "الدخول",
    "visa.processing": "المعالجة",
    "visa.processingFee": "رسوم المعالجة",
    "visa.requirements": "المتطلبات",
    "visa.validity": "الصلاحية",
    "footer.tagline": "شريكك الموثوق لرحلات الحج والعمرة",
    "footer.quickLinks": "روابط سريعة",
    "footer.services": "الخدمات",
    "footer.contact": "تواصل معنا",
    "footer.rights": "جميع الحقوق محفوظة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "common.allRatings": "جميع التقييمات",
    "common.allPrices": "جميع الأسعار",
    "common.perRoom": "لكل غرفة",
    "hotels.noResults": "لا توجد فنادق",
    "hotels.mapView": "عرض الخريطة",
    "hotels.listView": "عرض القائمة",
    "transport.private": "خاص",
    "transport.shared": "مشترك",
    "transport.pickup": "موقع الاستلام",
    "transport.dropoff": "موقع التوصيل",
    "tours.duration": "المدة",
    "tours.groupSize": "حجم المجموعة",
    "tours.guide": "المرشد",
    "tours.bookTour": "احجز الجولة",
    "store.quantity": "الكمية",
    "store.total": "الإجمالي",
    "store.emptyCart": "سلة التسوق فارغة",
    "store.continueShopping": "متابعة التسوق",
    "store.placeOrder": "تأكيد الطلب",
    "store.orderSuccess": "تم تقديم الطلب بنجاح!",
    "admin.add": "إضافة جديد",
    "admin.edit": "تعديل",
    "admin.delete": "حذف",
    "admin.save": "حفظ التغييرات",
    "admin.cancel": "إلغاء",
    "admin.hajj": "برامج الحج",
    "admin.umrah": "برامج العمرة",
    "admin.hotels": "الفنادق",
    "admin.flights": "الرحلات",
    "admin.visa": "أنواع التأشيرة",
    "admin.transport": "المواصلات",
    "admin.tours": "الجولات",
    "admin.store": "المتجر",
    "admin.analytics": "التحليلات",
    "common.internalPortal": "البوابة الداخلية",
    "common.externalPortal": "البوابة الخارجية",
    "hajj.nights": "ليالي",
    "hajj.includes": "يشمل",
    "hajj.economy": "اقتصادي",
    "hajj.premium": "مميز",
    "hajj.vip": "VIP",
    "umrah.nights": "ليالي",
    "umrah.includes": "يشمل",
    "umrah.economy": "اقتصادي",
    "umrah.premium": "مميز",
    "umrah.vip": "VIP",
  },
  ur: {
    "nav.hajj": "حج پروگرام",
    "nav.umrah": "عمرہ پروگرام",
    "nav.hotels": "ہوٹل",
    "nav.flights": "پروازیں",
    "nav.visa": "ویزا",
    "nav.transport": "ٹرانسپورٹ",
    "nav.tours": "زیارت ٹورز",
    "nav.store": "اسٹور",
    "nav.admin": "ایڈمن",
    "nav.login": "سائن ان",
    "nav.logout": "سائن آؤٹ",
    "nav.flexibleRequest": "کسٹم ریکوئسٹ",
    "nav.media": "میڈیا سینٹر",
    "nav.news": "خبریں",
    "home.hero.title1": "آپ کا مقدس سفر",
    "home.hero.title2": "یہاں سے شروع ہوتا ہے",
    "home.hero.subtitle": "گو عمرہ کے ساتھ اپنی زندگی کا سب سے بابرکت سفر کریں — حج، عمرہ اور تمام حج خدمات کے لیے آپ کا قابل اعتماد شریک۔",
    "home.hero.search": "حج، عمرہ، ہوٹل تلاش کریں...",
    "home.hero.cta.hajj": "حج پروگرام",
    "home.hero.cta.umrah": "عمرہ پیکجز",
    "home.services.title": "ہماری مکمل خدمات",
    "home.services.subtitle": "آپ کے مقدس سفر کے لیے سب کچھ ایک جگہ۔",
    "home.featured.title": "نمایاں پروگرام",
    "home.featured.subtitle": "ایک غیر معمولی روحانی تجربے کے لیے منتخب پیکجز۔",
    "common.bookNow": "ابھی بک کریں",
    "common.learnMore": "مزید جانیں",
    "common.viewAll": "سب دیکھیں",
    "common.search": "تلاش",
    "common.filter": "فلٹر",
    "common.sort": "ترتیب",
    "common.price": "قیمت",
    "common.duration": "مدت",
    "common.featured": "نمایاں",
    "common.urgent": "محدود نشستیں",
    "common.available": "دستیاب",
    "common.soldOut": "ختم ہو گیا",
    "common.from": "سے",
    "common.perPerson": "فی شخص",
    "common.perNight": "فی رات",
    "common.loading": "لوڈ ہو رہا ہے...",
    "common.noResults": "کوئی نتیجہ نہیں ملا۔",
    "common.days": "دن",
    "common.nights": "راتیں",
    "common.persons": "افراد",
    "common.submit": "جمع کریں",
    "common.cancel": "منسوخ",
    "common.save": "محفوظ کریں",
    "common.delete": "حذف کریں",
    "common.edit": "ترمیم",
    "common.add": "شامل کریں",
    "common.close": "بند کریں",
    "common.back": "واپس",
    "common.next": "اگلا",
    "common.confirm": "تصدیق",
    "hajj.title": "حج پروگرام",
    "hajj.subtitle": "پریمیم رہائش اور رہنمائی خدمات کے ساتھ مکمل حج پیکجز۔",
    "hajj.internal": "داخلی پروگرام",
    "hajj.external": "بیرونی پروگرام",
    "hajj.filter.all": "تمام پروگرام",
    "hajj.filter.economy": "اکانومی",
    "hajj.filter.standard": "معیاری",
    "hajj.filter.premium": "پریمیم",
    "hajj.filter.vip": "VIP",
    "umrah.title": "عمرہ پروگرام",
    "umrah.subtitle": "ہر حاجی کے لیے روحانی عمرہ پیکجز۔",
    "umrah.internal": "داخلی پروگرام",
    "umrah.external": "بیرونی پروگرام",
    "hotels.title": "ہوٹل بکنگ",
    "hotels.subtitle": "مسجد الحرام اور مسجد نبوی کے قریب پریمیم ہوٹل۔",
    "hotels.search.destination": "منزل",
    "hotels.search.checkin": "چیک ان",
    "hotels.search.checkout": "چیک آؤٹ",
    "hotels.search.guests": "مہمان",
    "hotels.filter.stars": "ستارہ درجہ بندی",
    "hotels.filter.price": "قیمت کی حد",
    "hotels.filter.proximity": "حرم سے قربت",
    "hotels.proximity.haram": "حرم سے فاصلہ",
    "flights.title": "فلائٹ بکنگ",
    "flights.subtitle": "جدہ اور مدینہ کے لیے براہ راست اور کنیکٹنگ پروازیں۔",
    "flights.from": "سے",
    "flights.to": "تک",
    "flights.depart": "روانگی",
    "flights.return": "واپسی",
    "flights.passengers": "مسافر",
    "flights.cabin": "کیبن کلاس",
    "flights.economy": "اکانومی",
    "flights.business": "بزنس",
    "flights.first": "فرسٹ کلاس",
    "visa.title": "ویزا خدمات",
    "visa.subtitle": "تمام حاجیوں کے لیے تیز اور قابل اعتماد ویزا پروسیسنگ۔",
    "visa.apply": "ابھی درخواست دیں",
    "visa.track": "درخواست ٹریک کریں",
    "visa.status": "حیثیت",
    "visa.umrah": "عمرہ ویزا",
    "visa.hajj": "حج ویزا",
    "visa.tourist": "سیاحتی ویزا",
    "visa.transit": "ٹرانزٹ ویزا",
    "transport.title": "ٹرانسپورٹ",
    "transport.subtitle": "مقدس شہروں میں VIP نجی ٹرانسفر اور گروپ ٹرانسپورٹ۔",
    "transport.from": "پک اپ مقام",
    "transport.to": "ڈراپ آف مقام",
    "transport.date": "سفر کی تاریخ",
    "transport.passengers": "مسافر",
    "transport.vip": "VIP کار",
    "transport.van": "وین",
    "transport.bus": "بس",
    "tours.title": "زیارت ٹورز",
    "tours.subtitle": "مکہ مکرمہ اور مدینہ منورہ میں رہنمائی دینی اور ثقافتی ٹورز۔",
    "tours.makkah": "مکہ ٹورز",
    "tours.madinah": "مدینہ ٹورز",
    "tours.religious": "مذہبی مقامات",
    "tours.cultural": "ثقافتی ٹورز",
    "tours.historical": "تاریخی مقامات",
    "store.title": "حج اسٹور",
    "store.subtitle": "آپ کے مقدس سفر کے لیے پریمیم ضروریات۔",
    "store.cart": "کارٹ",
    "store.checkout": "چیک آؤٹ",
    "store.addToCart": "کارٹ میں شامل کریں",
    "store.buyNow": "ابھی خریدیں",
    "store.inStock": "اسٹاک میں",
    "store.outOfStock": "اسٹاک ختم",
    "admin.title": "کمانڈ سینٹر",
    "admin.dashboard": "ڈیش بورڈ",
    "admin.localization": "لوکلائزیشن اور قیمت",
    "admin.pricing": "قیمت کا انتظام",
    "admin.users": "صارفین",
    "admin.bookings": "بکنگز",
    "admin.orders": "آرڈرز",
    "admin.settings": "ترتیبات",
    "lang.select": "زبان",
    "currency.select": "کرنسی",
    "bismillah": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "common.person": "فرد",
    "common.explore": "دریافت کریں",
    "badge.limited": "محدود نشستیں",
    "badge.featured": "نمایاں",
    "home.hero.badge": "50,000+ حاجیوں کا اعتماد",
    "home.hero.title": "آپ کا مقدس سفر",
    "home.hero.titleHighlight": "یہاں سے شروع ہوتا ہے",
    "home.hero.searchPlaceholder": "حج، عمرہ، ہوٹل تلاش کریں...",
    "home.services.badge": "ہماری خدمات",
    "home.services.hajj": "پریمیم رہائش اور ماہر رہنماؤں کے ساتھ مکمل حج پیکجز۔",
    "home.services.umrah": "ہر حاجی کے لیے روحانی عمرہ پیکجز۔",
    "home.services.hotels": "مسجد الحرام اور مسجد نبوی کے قریب پریمیم ہوٹل۔",
    "home.services.flights": "جدہ اور مدینہ کے لیے براہ راست اور کنیکٹنگ پروازیں۔",
    "home.services.visa": "تمام حاجیوں کے لیے تیز اور قابل اعتماد ویزا پروسیسنگ۔",
    "home.services.transport": "مقدس شہروں میں VIP نجی ٹرانسفر اور گروپ ٹرانسپورٹ۔",
    "home.services.tours": "مکہ مکرمہ اور مدینہ منورہ میں رہنمائی دینی اور ثقافتی ٹورز۔",
    "home.services.store": "آپ کے مقدس سفر کے لیے پریمیم ضروریات۔",
    "home.stats.pilgrims": "خوش حاجی",
    "home.stats.years": "سال تجربہ",
    "home.stats.satisfaction": "اطمینان کی شرح",
    "home.stats.support": "سپورٹ دستیاب",
    "home.hajj.badge": "حج پروگرام",
    "home.hajj.title": "نمایاں حج پیکجز",
    "home.umrah.badge": "عمرہ پروگرام",
    "home.umrah.title": "نمایاں عمرہ پیکجز",
    "home.why.badge": "گو عمرہ کیوں",
    "home.why.title": "آپ کا سفر، ہماری",
    "home.why.titleHighlight": "ذمہ داری",
    "home.why.subtitle": "15 سال سے زیادہ کے تجربے کے ساتھ، گو عمرہ نے 50,000 سے زیادہ حاجیوں کی رہنمائی کی ہے۔",
    "home.why.cta": "اپنا سفر شروع کریں",
    "home.testimonials.badge": "گواہیاں",
    "home.testimonials.title": "ہمارے حاجی کیا کہتے ہیں",
    "home.testimonials.t1": "گو عمرہ نے ہمارے حج کے تجربے کو واقعی ناقابل فراموش بنا دیا۔ تفصیلات پر توجہ، رہنمائی، اور پوری رحلت میں مدد غیر معمولی تھی۔",
    "home.testimonials.t2": "ہم 6 افراد کے خاندان کے طور پر عمرہ کے لیے سفر کیا اور سب کچھ بالکل ترتیب دیا گیا تھا۔ ہوٹل حرم سے چند قدم کے فاصلے پر تھا۔",
    "home.testimonials.t3": "ویزا پروسیسنگ تیز اور پریشانی سے پاک تھی۔ زیارت ٹورز ناقابل یقین حد تک معلوماتی اور روحانی طور پر افزودہ تھے۔",
    "home.cta.title": "کیا آپ اپنا مقدس سفر شروع کرنے کے لیے تیار ہیں؟",
    "home.cta.subtitle": "ہزاروں حاجیوں میں شامل ہوں جنہوں نے اپنے حج اور عمرہ کے تجربات کے لیے گو عمرہ پر اعتماد کیا۔",
    "home.cta.hajjBtn": "حج پیکج بک کریں",
    "home.cta.umrahBtn": "عمرہ پیکج بک کریں",
    "home.features.licensed": "حکومت سے لائسنس یافتہ اور تصدیق شدہ",
    "home.features.multilingual": "کثیر لسانی سپورٹ (6 زبانیں)",
    "home.features.transparent": "شفاف قیمتیں — کوئی پوشیدہ فیس نہیں",
    "home.features.payment": "لچکدار ادائیگی کے منصوبے دستیاب",
    "home.features.realtime": "فوری بکنگ کی تصدیق",
    "home.features.insurance": "مکمل سفری بیمہ شامل",
    "common.hide": "چھپائیں",
    "common.view": "دیکھیں",
    "visa.applyNow": "ابھی اپلائی کریں",
    "visa.entry": "داخلہ",
    "visa.processing": "پروسیسنگ",
    "visa.processingFee": "پروسیسنگ فیس",
    "visa.requirements": "ضروریات",
    "visa.validity": "مدت صلاحیت",
    "footer.tagline": "حج و عمرہ کے سفر کے لیے آپ کا قابل بھروسہ ساتھی",
    "footer.quickLinks": "تیز روابط",
    "footer.services": "خدمات",
    "footer.contact": "ہم سے رابطہ کریں",
    "footer.rights": "تمام حقوق محفوظ ہیں",
    "footer.privacy": "رازداری پالیسی",
    "footer.terms": "خدمت کی شرائط",
    "common.allRatings": "تمام ریٹنگز",
    "common.allPrices": "تمام قیمتیں",
    "common.perRoom": "فی کمرہ",
    "hotels.noResults": "کوئی ہوٹل نہیں ملا",
    "hotels.mapView": "نقشہ دیکھیں",
    "hotels.listView": "فہرست دیکھیں",
    "transport.private": "نجی",
    "transport.shared": "مشترکہ",
    "transport.pickup": "استقبال کی جگہ",
    "transport.dropoff": "چھوڑنے کی جگہ",
    "tours.duration": "مدت",
    "tours.groupSize": "گروپ کا سائز",
    "tours.guide": "رہنما",
    "tours.bookTour": "ٹور بک کریں",
    "store.quantity": "تعداد",
    "store.total": "کل رقم",
    "store.emptyCart": "کارٹ خالی ہے",
    "store.continueShopping": "خریداری جاری رکھیں",
    "store.placeOrder": "آرڈر دیں",
    "store.orderSuccess": "آرڈر کامیابی سے دے دیا گیا!",
    "admin.add": "نیا شامل کریں",
    "admin.edit": "ترمیم",
    "admin.delete": "حذف کریں",
    "admin.save": "تبدیلیاں محفوظ کریں",
    "admin.cancel": "منسوخہ",
    "admin.hajj": "حج پروگرام",
    "admin.umrah": "عمرہ پروگرام",
    "admin.hotels": "ہوٹل",
    "admin.flights": "پروازیں",
    "admin.visa": "ویزہ اقسام",
    "admin.transport": "ٹرانسپورٹ",
    "admin.tours": "ٹورز",
    "admin.store": "اسٹور",
    "admin.analytics": "تجزیہ",
    "common.internalPortal": "اندرونی پورٹل",
    "common.externalPortal": "بیرونی پورٹل",
    "hajj.nights": "راتیں",
    "hajj.includes": "شامل ہے",
    "hajj.economy": "اقتصادی",
    "hajj.premium": "پریمیم",
    "hajj.vip": "VIP",
    "umrah.nights": "راتیں",
    "umrah.includes": "شامل ہے",
    "umrah.economy": "اقتصادی",
    "umrah.premium": "پریمیم",
    "umrah.vip": "VIP",
  },
  tr: {
    "nav.hajj": "Hac Programları",
    "nav.umrah": "Umre Programları",
    "nav.hotels": "Oteller",
    "nav.flights": "Uçuşlar",
    "nav.visa": "Vize",
    "nav.transport": "Ulaşım",
    "nav.tours": "Ziyaret Turları",
    "nav.store": "Mağaza",
    "nav.admin": "Yönetim",
    "nav.login": "Giriş Yap",
    "nav.logout": "Çıkış Yap",
    "nav.flexibleRequest": "Özel Talep",
    "nav.media": "Medya Merkezi",
    "nav.news": "Haberler",
    "home.hero.title1": "Kutsal Yolculuğunuz",
    "home.hero.title2": "Burada Başlıyor",
    "home.hero.subtitle": "Go Umrah ile hayatınızın en kutsal yolculuğunu yaşayın — Hac, Umre ve tüm hac hizmetleri için güvenilir ortağınız.",
    "home.hero.search": "Hac, Umre, Otel ara...",
    "home.hero.cta.hajj": "Hac Programları",
    "home.hero.cta.umrah": "Umre Paketleri",
    "home.services.title": "Eksiksiz Hizmetlerimiz",
    "home.services.subtitle": "Kutsal yolculuğunuz için ihtiyacınız olan her şey tek bir yerde.",
    "home.featured.title": "Öne Çıkan Programlar",
    "home.featured.subtitle": "Olağanüstü bir manevi deneyim için özenle seçilmiş paketler.",
    "common.bookNow": "Şimdi Rezervasyon",
    "common.learnMore": "Daha Fazla",
    "common.viewAll": "Tümünü Gör",
    "common.search": "Ara",
    "common.filter": "Filtrele",
    "common.sort": "Sırala",
    "common.price": "Fiyat",
    "common.duration": "Süre",
    "common.featured": "Öne Çıkan",
    "common.urgent": "Sınırlı Koltuk",
    "common.available": "Mevcut",
    "common.soldOut": "Tükendi",
    "common.from": "İtibaren",
    "common.perPerson": "kişi başı",
    "common.perNight": "gecelik",
    "common.loading": "Yükleniyor...",
    "common.noResults": "Sonuç bulunamadı.",
    "common.days": "gün",
    "common.nights": "gece",
    "common.persons": "kişi",
    "common.submit": "Gönder",
    "common.cancel": "İptal",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.add": "Ekle",
    "common.close": "Kapat",
    "common.back": "Geri",
    "common.next": "İleri",
    "common.confirm": "Onayla",
    "hajj.title": "Hac Programları",
    "hajj.subtitle": "Premium konaklama ve rehberli hizmetlerle eksiksiz Hac paketleri.",
    "hajj.internal": "Dahili Programlar",
    "hajj.external": "Harici Programlar",
    "hajj.filter.all": "Tüm Programlar",
    "hajj.filter.economy": "Ekonomi",
    "hajj.filter.standard": "Standart",
    "hajj.filter.premium": "Premium",
    "hajj.filter.vip": "VIP",
    "umrah.title": "Umre Programları",
    "umrah.subtitle": "Her hacı için özel manevi Umre paketleri.",
    "umrah.internal": "Dahili Programlar",
    "umrah.external": "Harici Programlar",
    "hotels.title": "Otel Rezervasyonu",
    "hotels.subtitle": "Mescid-i Haram ve Mescid-i Nebevi yakınında premium oteller.",
    "hotels.search.destination": "Destinasyon",
    "hotels.search.checkin": "Giriş",
    "hotels.search.checkout": "Çıkış",
    "hotels.search.guests": "Misafirler",
    "hotels.filter.stars": "Yıldız Derecesi",
    "hotels.filter.price": "Fiyat Aralığı",
    "hotels.filter.proximity": "Harem'e Yakınlık",
    "hotels.proximity.haram": "Harem'e Mesafe",
    "flights.title": "Uçuş Rezervasyonu",
    "flights.subtitle": "Cidde ve Medine'ye direkt ve aktarmalı uçuşlar.",
    "flights.from": "Nereden",
    "flights.to": "Nereye",
    "flights.depart": "Kalkış",
    "flights.return": "Dönüş",
    "flights.passengers": "Yolcular",
    "flights.cabin": "Kabin Sınıfı",
    "flights.economy": "Ekonomi",
    "flights.business": "Business",
    "flights.first": "Birinci Sınıf",
    "visa.title": "Vize Hizmetleri",
    "visa.subtitle": "Tüm hacılar için hızlı ve güvenilir vize işleme.",
    "visa.apply": "Şimdi Başvur",
    "visa.track": "Başvuruyu Takip Et",
    "visa.status": "Durum",
    "visa.umrah": "Umre Vizesi",
    "visa.hajj": "Hac Vizesi",
    "visa.tourist": "Turist Vizesi",
    "visa.transit": "Transit Vize",
    "transport.title": "Ulaşım",
    "transport.subtitle": "Kutsal şehirlerde VIP özel transfer ve grup ulaşımı.",
    "transport.from": "Alış Noktası",
    "transport.to": "Bırakış Noktası",
    "transport.date": "Seyahat Tarihi",
    "transport.passengers": "Yolcular",
    "transport.vip": "VIP Araç",
    "transport.van": "Van",
    "transport.bus": "Otobüs",
    "tours.title": "Ziyaret Turları",
    "tours.subtitle": "Mekke ve Medine'de rehberli dini ve kültürel turlar.",
    "tours.makkah": "Mekke Turları",
    "tours.madinah": "Medine Turları",
    "tours.religious": "Dini Mekanlar",
    "tours.cultural": "Kültürel Turlar",
    "tours.historical": "Tarihi Mekanlar",
    "store.title": "Hac Mağazası",
    "store.subtitle": "Kutsal yolculuğunuz için premium malzemeler.",
    "store.cart": "Sepet",
    "store.checkout": "Ödeme",
    "store.addToCart": "Sepete Ekle",
    "store.buyNow": "Hemen Al",
    "store.inStock": "Stokta Var",
    "store.outOfStock": "Stokta Yok",
    "admin.title": "Komuta Merkezi",
    "admin.dashboard": "Gösterge Paneli",
    "admin.localization": "Yerelleştirme ve Fiyatlandırma",
    "admin.pricing": "Fiyat Yönetimi",
    "admin.users": "Kullanıcılar",
    "admin.bookings": "Rezervasyonlar",
    "admin.orders": "Siparişler",
    "admin.settings": "Ayarlar",
    "lang.select": "Dil",
    "currency.select": "Para Birimi",
    "bismillah": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "common.person": "kişi",
    "common.explore": "Keşfet",
    "badge.limited": "Sınırlı Koltuk",
    "badge.featured": "Öne Çıkan",
    "home.hero.badge": "50.000+ Hacı Tarafından Güvenilen",
    "home.hero.title": "Kutsal Yolculuğunuz",
    "home.hero.titleHighlight": "Burada Başlıyor",
    "home.hero.searchPlaceholder": "Hac, Umre, Otel ara...",
    "home.services.badge": "Hizmetlerimiz",
    "home.services.hajj": "Premium konaklama ve uzman rehberlerle eksiksiz Hac paketleri.",
    "home.services.umrah": "Her hacı için özel manevi Umre paketleri.",
    "home.services.hotels": "Mescid-i Haram ve Mescid-i Nebevi yakınında premium oteller.",
    "home.services.flights": "Cidde ve Medine'ye direkt ve aktarmalı uçuşlar.",
    "home.services.visa": "Tüm hacılar için hızlı ve güvenilir vize işleme.",
    "home.services.transport": "Kutsal şehirlerde VIP özel transfer ve grup ulaşımı.",
    "home.services.tours": "Mekke ve Medine'de rehberli dini ve kültürel turlar.",
    "home.services.store": "Kutsal yolculuğunuz için premium malzemeler.",
    "home.stats.pilgrims": "Mutlu Hacı",
    "home.stats.years": "Yıl Deneyim",
    "home.stats.satisfaction": "Memnuniyet Oranı",
    "home.stats.support": "Destek Mevcut",
    "home.hajj.badge": "Hac Programları",
    "home.hajj.title": "Öne Çıkan Hac Paketleri",
    "home.umrah.badge": "Umre Programları",
    "home.umrah.title": "Öne Çıkan Umre Paketleri",
    "home.why.badge": "Neden Go Umrah",
    "home.why.title": "Yolculuğunuz, Bizim",
    "home.why.titleHighlight": "Taahhüdümüz",
    "home.why.subtitle": "15 yılı aşkın deneyimimizle Go Umrah, 50.000'den fazla hacıya kutsal yolculuklarında rehberlik etti.",
    "home.why.cta": "Yolculuğunuzu Başlatın",
    "home.testimonials.badge": "Referanslar",
    "home.testimonials.title": "Hacılarımız Ne Diyor",
    "home.testimonials.t1": "Go Umrah, Hac deneyimimizi gerçekten unutulmaz kıldı. Detaylara verilen önem, rehberlik ve yolculuk boyunca destek olağanüstüydü.",
    "home.testimonials.t2": "6 kişilik bir aile olarak Umre için seyahat ettik ve her şey mükemmel şekilde ayarlandı. Otel Harem'e birkaç adım uzaklıktaydı.",
    "home.testimonials.t3": "Vize işlemi hızlı ve sorunsuzdu. Ziyaret turları inanılmaz derecede bilgilendirici ve manevi açıdan zenginleştiriciydi.",
    "home.cta.title": "Kutsal Yolculuğunuza Başlamaya Hazır mısınız?",
    "home.cta.subtitle": "Hac ve Umre deneyimleri için Go Umrah'a güvenen binlerce hacıya katılın.",
    "home.cta.hajjBtn": "Hac Paketi Rezervasyonu",
    "home.cta.umrahBtn": "Umre Paketi Rezervasyonu",
    "home.features.licensed": "Devlet Lisanslı ve Sertifikalı",
    "home.features.multilingual": "Çok Dilli Destek (6 Dil)",
    "home.features.transparent": "Şeffaf Fiyatlandırma — Gizli Ücret Yok",
    "home.features.payment": "Esnek Ödeme Planları Mevcut",    "home.features.realtime": "Gerçek Zamanlı Rezervasyon Onaylı",
    "home.features.insurance": "Tam Seyahat Sigortası Dahil",
    "common.hide": "Gizle",
    "common.view": "Gör",
    "visa.applyNow": "Hemen Başvur",
    "visa.entry": "Giriş",
    "visa.processing": "İşleme",
    "visa.processingFee": "İşlem Ücret",
    "visa.requirements": "Gereksinimler",
    "visa.validity": "Geçerlilik",
    "footer.tagline": "Hac ve Umre yolculuklarınız için güvenilir ortağınız",
    "footer.quickLinks": "Hızlı Bağlantılar",
    "footer.services": "Hizmetler",
    "footer.contact": "Bize Ulaşın",
    "footer.rights": "Tüm haklar saklıdır",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Hizmet Koşulları",
    "common.allRatings": "Tüm Puanlar",
    "common.allPrices": "Tüm Fiyatlar",
    "common.perRoom": "oda başına",
    "hotels.noResults": "Otel bulunamadı",
    "hotels.mapView": "Harita Görünümü",
    "hotels.listView": "Liste Görünümü",
    "transport.private": "Özel",
    "transport.shared": "Paylaşımlı",
    "transport.pickup": "Alış Noktası",
    "transport.dropoff": "Bırakış Noktası",
    "tours.duration": "Süre",
    "tours.groupSize": "Grup Boyutu",
    "tours.guide": "Rehber",
    "tours.bookTour": "Turu Rezerve Et",
    "store.quantity": "Miktar",
    "store.total": "Toplam",
    "store.emptyCart": "Sepetin boş",
    "store.continueShopping": "Alışverişe Devam Et",
    "store.placeOrder": "Sipariş Ver",
    "store.orderSuccess": "Sipariş başarıyla verildi!",
    "admin.add": "Yeni Ekle",
    "admin.edit": "Düzenle",
    "admin.delete": "Sil",
    "admin.save": "Değişiklikleri Kaydet",
    "admin.cancel": "İptal",
    "admin.hajj": "Hac Programları",
    "admin.umrah": "Umre Programları",
    "admin.hotels": "Oteller",
    "admin.flights": "Uçuşlar",
    "admin.visa": "Vize Türleri",
    "admin.transport": "Ulaşım",
    "admin.tours": "Turlar",
    "admin.store": "Mağaza",
    "admin.analytics": "Analitik",
    "common.internalPortal": "İç Portal",
    "common.externalPortal": "Dış Portal",
    "hajj.nights": "Gece",
    "hajj.includes": "İçerir",
    "hajj.economy": "Ekonomi",
    "hajj.premium": "Premium",
    "hajj.vip": "VIP",
    "umrah.nights": "Gece",
    "umrah.includes": "İçerir",
    "umrah.economy": "Ekonomi",
    "umrah.premium": "Premium",
    "umrah.vip": "VIP",
  },
  id: {
    "nav.hajj": "Program Haji",
    "nav.umrah": "Program Umrah",
    "nav.hotels": "Hotel",
    "nav.flights": "Penerbangan",
    "nav.visa": "Visa",
    "nav.transport": "Transportasi",
    "nav.tours": "Wisata Ziarah",
    "nav.store": "Toko",
    "nav.admin": "Admin",
    "nav.login": "Masuk",
    "nav.logout": "Keluar",
    "nav.flexibleRequest": "Permintaan Khusus",
    "nav.media": "Pusat Media",
    "nav.news": "Berita",
    "home.hero.title1": "Perjalanan Suci Anda",
    "home.hero.title2": "Dimulai Di Sini",
    "home.hero.subtitle": "Rasakan perjalanan paling berkah dalam hidup Anda bersama Go Umrah — mitra terpercaya Anda untuk Haji, Umrah, dan semua layanan ibadah.",
    "home.hero.search": "Cari Haji, Umrah, Hotel...",
    "home.hero.cta.hajj": "Program Haji",
    "home.hero.cta.umrah": "Paket Umrah",
    "home.services.title": "Layanan Lengkap Kami",
    "home.services.subtitle": "Semua yang Anda butuhkan untuk perjalanan suci, dalam satu tempat.",
    "home.featured.title": "Program Unggulan",
    "home.featured.subtitle": "Paket pilihan untuk pengalaman spiritual yang luar biasa.",
    "common.bookNow": "Pesan Sekarang",
    "common.learnMore": "Pelajari Lebih",
    "common.viewAll": "Lihat Semua",
    "common.search": "Cari",
    "common.filter": "Filter",
    "common.sort": "Urutkan",
    "common.price": "Harga",
    "common.duration": "Durasi",
    "common.featured": "Unggulan",
    "common.urgent": "Kursi Terbatas",
    "common.available": "Tersedia",
    "common.soldOut": "Habis Terjual",
    "common.from": "Mulai",
    "common.perPerson": "per orang",
    "common.perNight": "per malam",
    "common.loading": "Memuat...",
    "common.noResults": "Tidak ada hasil.",
    "common.days": "hari",
    "common.nights": "malam",
    "common.persons": "orang",
    "common.submit": "Kirim",
    "common.cancel": "Batal",
    "common.save": "Simpan",
    "common.delete": "Hapus",
    "common.edit": "Edit",
    "common.add": "Tambah",
    "common.close": "Tutup",
    "common.back": "Kembali",
    "common.next": "Selanjutnya",
    "common.confirm": "Konfirmasi",
    "hajj.title": "Program Haji",
    "hajj.subtitle": "Paket Haji lengkap dengan akomodasi premium dan layanan berpemandu.",
    "hajj.internal": "Program Internal",
    "hajj.external": "Program Eksternal",
    "hajj.filter.all": "Semua Program",
    "hajj.filter.economy": "Ekonomi",
    "hajj.filter.standard": "Standar",
    "hajj.filter.premium": "Premium",
    "hajj.filter.vip": "VIP",
    "umrah.title": "Program Umrah",
    "umrah.subtitle": "Paket Umrah spiritual yang disesuaikan untuk setiap jamaah.",
    "umrah.internal": "Program Internal",
    "umrah.external": "Program Eksternal",
    "hotels.title": "Pemesanan Hotel",
    "hotels.subtitle": "Hotel premium dekat Masjidil Haram dan Masjid Nabawi.",
    "hotels.search.destination": "Tujuan",
    "hotels.search.checkin": "Check-in",
    "hotels.search.checkout": "Check-out",
    "hotels.search.guests": "Tamu",
    "hotels.filter.stars": "Rating Bintang",
    "hotels.filter.price": "Rentang Harga",
    "hotels.filter.proximity": "Kedekatan ke Haram",
    "hotels.proximity.haram": "Jarak ke Haram",
    "flights.title": "Pemesanan Penerbangan",
    "flights.subtitle": "Penerbangan langsung dan transit ke Jeddah & Madinah.",
    "flights.from": "Dari",
    "flights.to": "Ke",
    "flights.depart": "Keberangkatan",
    "flights.return": "Kepulangan",
    "flights.passengers": "Penumpang",
    "flights.cabin": "Kelas Kabin",
    "flights.economy": "Ekonomi",
    "flights.business": "Bisnis",
    "flights.first": "Kelas Satu",
    "visa.title": "Layanan Visa",
    "visa.subtitle": "Pemrosesan visa cepat dan terpercaya untuk semua jamaah.",
    "visa.apply": "Daftar Sekarang",
    "visa.track": "Lacak Permohonan",
    "visa.status": "Status",
    "visa.umrah": "Visa Umrah",
    "visa.hajj": "Visa Haji",
    "visa.tourist": "Visa Turis",
    "visa.transit": "Visa Transit",
    "transport.title": "Transportasi",
    "transport.subtitle": "Transfer pribadi VIP dan transportasi kelompok di Kota Suci.",
    "transport.from": "Lokasi Jemput",
    "transport.to": "Lokasi Antar",
    "transport.date": "Tanggal Perjalanan",
    "transport.passengers": "Penumpang",
    "transport.vip": "Mobil VIP",
    "transport.van": "Van",
    "transport.bus": "Bus",
    "tours.title": "Wisata Ziarah",
    "tours.subtitle": "Tur religi dan budaya berpemandu di Makkah dan Madinah.",
    "tours.makkah": "Tur Makkah",
    "tours.madinah": "Tur Madinah",
    "tours.religious": "Situs Religi",
    "tours.cultural": "Tur Budaya",
    "tours.historical": "Situs Bersejarah",
    "store.title": "Toko Haji",
    "store.subtitle": "Perlengkapan premium untuk perjalanan suci Anda.",
    "store.cart": "Keranjang",
    "store.checkout": "Checkout",
    "store.addToCart": "Tambah ke Keranjang",
    "store.buyNow": "Beli Sekarang",
    "store.inStock": "Tersedia",
    "store.outOfStock": "Habis",
    "admin.title": "Pusat Komando",
    "admin.dashboard": "Dasbor",
    "admin.localization": "Lokalisasi & Harga",
    "admin.pricing": "Manajemen Harga",
    "admin.users": "Pengguna",
    "admin.bookings": "Pemesanan",
    "admin.orders": "Pesanan",
    "admin.settings": "Pengaturan",
    "lang.select": "Bahasa",
    "currency.select": "Mata Uang",
    "bismillah": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "common.person": "orang",
    "common.explore": "Jelajahi",
    "badge.limited": "Kursi Terbatas",
    "badge.featured": "Unggulan",
    "home.hero.badge": "Dipercaya oleh 50.000+ Jamaah",
    "home.hero.title": "Perjalanan Suci Anda",
    "home.hero.titleHighlight": "Dimulai Di Sini",
    "home.hero.searchPlaceholder": "Cari Haji, Umrah, Hotel...",
    "home.services.badge": "Layanan Kami",
    "home.services.hajj": "Paket Haji lengkap dengan akomodasi premium dan pemandu ahli.",
    "home.services.umrah": "Paket Umrah spiritual yang disesuaikan untuk setiap jamaah.",
    "home.services.hotels": "Hotel premium dekat Masjidil Haram dan Masjid Nabawi.",
    "home.services.flights": "Penerbangan langsung dan transit ke Jeddah & Madinah.",
    "home.services.visa": "Pemrosesan visa cepat dan terpercaya untuk semua jamaah.",
    "home.services.transport": "Transfer pribadi VIP dan transportasi kelompok di Kota Suci.",
    "home.services.tours": "Tur religi dan budaya berpemandu di Makkah dan Madinah.",
    "home.services.store": "Perlengkapan premium untuk perjalanan suci Anda.",
    "home.stats.pilgrims": "Jamaah Puas",
    "home.stats.years": "Tahun Pengalaman",
    "home.stats.satisfaction": "Tingkat Kepuasan",
    "home.stats.support": "Dukungan Tersedia",
    "home.hajj.badge": "Program Haji",
    "home.hajj.title": "Paket Haji Unggulan",
    "home.umrah.badge": "Program Umrah",
    "home.umrah.title": "Paket Umrah Unggulan",
    "home.why.badge": "Mengapa Go Umrah",
    "home.why.title": "Perjalanan Anda, Komitmen",
    "home.why.titleHighlight": "Kami",
    "home.why.subtitle": "Dengan pengalaman lebih dari 15 tahun, Go Umrah telah membimbing lebih dari 50.000 jamaah dalam perjalanan suci mereka.",
    "home.why.cta": "Mulai Perjalanan Anda",
    "home.testimonials.badge": "Testimoni",
    "home.testimonials.title": "Apa Kata Jamaah Kami",
    "home.testimonials.t1": "Go Umrah membuat pengalaman Haji kami benar-benar tak terlupakan. Perhatian terhadap detail, bimbingan, dan dukungan sepanjang perjalanan sangat luar biasa.",
    "home.testimonials.t2": "Kami bepergian sebagai keluarga 6 orang untuk Umrah dan semuanya diatur dengan sempurna. Hotel hanya beberapa langkah dari Haram.",
    "home.testimonials.t3": "Pemrosesan visa cepat dan bebas masalah. Wisata Ziarah sangat informatif dan memperkaya spiritual.",
    "home.cta.title": "Siap Memulai Perjalanan Suci Anda?",
    "home.cta.subtitle": "Bergabunglah dengan ribuan jamaah yang telah mempercayai Go Umrah untuk pengalaman Haji dan Umrah mereka.",
    "home.cta.hajjBtn": "Pesan Paket Haji",
    "home.cta.umrahBtn": "Pesan Paket Umrah",
    "home.features.licensed": "Berlisensi & Bersertifikat Pemerintah",
    "home.features.multilingual": "Dukungan Multibahasa (6 Bahasa)",
    "home.features.transparent": "Harga Transparan — Tanpa Biaya Tersembunyi",
    "home.features.payment": "Rencana Pembayaran Fleksibel Tersedia",
    "home.features.realtime": "Konfirmasi Pemesanan Real-time",
    "home.features.insurance": "Asuransi Perjalanan Penuh Termasuk",
    "common.hide": "Sembunyikan",
    "common.view": "Lihat",
    "visa.applyNow": "Daftar Sekarang",
    "visa.entry": "Masuk",
    "visa.processing": "Pemrosesan",
    "visa.processingFee": "Biaya Pemrosesan",
    "visa.requirements": "Persyaratan",
    "visa.validity": "Masa Berlaku",
    "footer.tagline": "Mitra terpercaya Anda untuk perjalanan Haji & Umrah",
    "footer.quickLinks": "Tautan Cepat",
    "footer.services": "Layanan",
    "footer.contact": "Hubungi Kami",
    "footer.rights": "Semua hak dilindungi",
    "footer.privacy": "Kebijakan Privasi",
    "footer.terms": "Syarat Layanan",
    "common.allRatings": "Semua Rating",
    "common.allPrices": "Semua Harga",
    "common.perRoom": "per kamar",
    "hotels.noResults": "Tidak ada hotel ditemukan",
    "hotels.mapView": "Tampilan Peta",
    "hotels.listView": "Tampilan Daftar",
    "transport.private": "Pribadi",
    "transport.shared": "Bersama",
    "transport.pickup": "Lokasi Penjemputan",
    "transport.dropoff": "Lokasi Pengantaran",
    "tours.duration": "Durasi",
    "tours.groupSize": "Ukuran Grup",
    "tours.guide": "Pemandu",
    "tours.bookTour": "Pesan Tur",
    "store.quantity": "Jumlah",
    "store.total": "Total",
    "store.emptyCart": "Keranjang kosong",
    "store.continueShopping": "Lanjut Belanja",
    "store.placeOrder": "Buat Pesanan",
    "store.orderSuccess": "Pesanan berhasil dibuat!",
    "admin.add": "Tambah Baru",
    "admin.edit": "Edit",
    "admin.delete": "Hapus",
    "admin.save": "Simpan Perubahan",
    "admin.cancel": "Batal",
    "admin.hajj": "Program Haji",
    "admin.umrah": "Program Umrah",
    "admin.hotels": "Hotel",
    "admin.flights": "Penerbangan",
    "admin.visa": "Jenis Visa",
    "admin.transport": "Transportasi",
    "admin.tours": "Wisata",
    "admin.store": "Toko",
    "admin.analytics": "Analitik",
    "common.internalPortal": "Portal Internal",
    "common.externalPortal": "Portal Eksternal",
    "hajj.nights": "Malam",
    "hajj.includes": "Termasuk",
    "hajj.economy": "Ekonomi",
    "hajj.premium": "Premium",
    "hajj.vip": "VIP",
    "umrah.nights": "Malam",
    "umrah.includes": "Termasuk",
    "umrah.economy": "Ekonomi",
    "umrah.premium": "Premium",
    "umrah.vip": "VIP",
  },
  fr: {
    "nav.hajj": "Programmes Hajj",
    "nav.umrah": "Programmes Omra",
    "nav.hotels": "Hôtels",
    "nav.flights": "Vols",
    "nav.visa": "Visa",
    "nav.transport": "Transport",
    "nav.tours": "Visites Ziyarat",
    "nav.store": "Boutique",
    "nav.admin": "Administration",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "nav.flexibleRequest": "Demande Personnalisée",
    "nav.media": "Centre Médias",
    "nav.news": "Actualités",
    "home.hero.title1": "Votre Voyage Sacré",
    "home.hero.title2": "Commence Ici",
    "home.hero.subtitle": "Vivez le voyage le plus béni de votre vie avec Go Umrah — votre partenaire de confiance pour le Hajj, l'Omra et tous les services de pèlerinage.",
    "home.hero.search": "Rechercher Hajj, Omra, Hôtels...",
    "home.hero.cta.hajj": "Programmes Hajj",
    "home.hero.cta.umrah": "Forfaits Omra",
    "home.services.title": "Nos Services Complets",
    "home.services.subtitle": "Tout ce dont vous avez besoin pour votre pèlerinage sacré, en un seul endroit.",
    "home.featured.title": "Programmes en Vedette",
    "home.featured.subtitle": "Des forfaits soigneusement sélectionnés pour une expérience spirituelle exceptionnelle.",
    "common.bookNow": "Réserver",
    "common.learnMore": "En Savoir Plus",
    "common.viewAll": "Voir Tout",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.price": "Prix",
    "common.duration": "Durée",
    "common.featured": "En Vedette",
    "common.urgent": "Places Limitées",
    "common.available": "Disponible",
    "common.soldOut": "Épuisé",
    "common.from": "À partir de",
    "common.perPerson": "par personne",
    "common.perNight": "par nuit",
    "common.loading": "Chargement...",
    "common.noResults": "Aucun résultat.",
    "common.days": "jours",
    "common.nights": "nuits",
    "common.persons": "personnes",
    "common.submit": "Soumettre",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.add": "Ajouter",
    "common.close": "Fermer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.confirm": "Confirmer",
    "hajj.title": "Programmes Hajj",
    "hajj.subtitle": "Forfaits Hajj complets avec hébergement premium et services guidés.",
    "hajj.internal": "Programmes Internes",
    "hajj.external": "Programmes Externes",
    "hajj.filter.all": "Tous les Programmes",
    "hajj.filter.economy": "Économie",
    "hajj.filter.standard": "Standard",
    "hajj.filter.premium": "Premium",
    "hajj.filter.vip": "VIP",
    "umrah.title": "Programmes Omra",
    "umrah.subtitle": "Forfaits Omra spirituels adaptés à chaque pèlerin.",
    "umrah.internal": "Programmes Internes",
    "umrah.external": "Programmes Externes",
    "hotels.title": "Réservation d'Hôtel",
    "hotels.subtitle": "Hôtels premium près de la Mosquée Al-Haram et de la Mosquée du Prophète.",
    "hotels.search.destination": "Destination",
    "hotels.search.checkin": "Arrivée",
    "hotels.search.checkout": "Départ",
    "hotels.search.guests": "Voyageurs",
    "hotels.filter.stars": "Classement Étoiles",
    "hotels.filter.price": "Fourchette de Prix",
    "hotels.filter.proximity": "Proximité du Haram",
    "hotels.proximity.haram": "Distance du Haram",
    "flights.title": "Réservation de Vol",
    "flights.subtitle": "Vols directs et avec escales vers Djeddah et Médine.",
    "flights.from": "De",
    "flights.to": "À",
    "flights.depart": "Départ",
    "flights.return": "Retour",
    "flights.passengers": "Passagers",
    "flights.cabin": "Classe Cabine",
    "flights.economy": "Économique",
    "flights.business": "Affaires",
    "flights.first": "Première Classe",
    "visa.title": "Services Visa",
    "visa.subtitle": "Traitement de visa rapide et fiable pour tous les pèlerins.",
    "visa.apply": "Postuler Maintenant",
    "visa.track": "Suivre la Demande",
    "visa.status": "Statut",
    "visa.umrah": "Visa Omra",
    "visa.hajj": "Visa Hajj",
    "visa.tourist": "Visa Touristique",
    "visa.transit": "Visa Transit",
    "transport.title": "Transport",
    "transport.subtitle": "Transferts privés VIP et transport de groupe dans les Villes Saintes.",
    "transport.from": "Lieu de Prise en Charge",
    "transport.to": "Lieu de Dépose",
    "transport.date": "Date de Voyage",
    "transport.passengers": "Passagers",
    "transport.vip": "Voiture VIP",
    "transport.van": "Van",
    "transport.bus": "Bus",
    "tours.title": "Visites Ziyarat",
    "tours.subtitle": "Visites religieuses et culturelles guidées à La Mecque et Médine.",
    "tours.makkah": "Visites La Mecque",
    "tours.madinah": "Visites Médine",
    "tours.religious": "Sites Religieux",
    "tours.cultural": "Visites Culturelles",
    "tours.historical": "Sites Historiques",
    "store.title": "Boutique Pèlerinage",
    "store.subtitle": "Essentiels premium pour votre voyage sacré.",
    "store.cart": "Panier",
    "store.checkout": "Paiement",
    "store.addToCart": "Ajouter au Panier",
    "store.buyNow": "Acheter Maintenant",
    "store.inStock": "En Stock",
    "store.outOfStock": "Épuisé",
    "admin.title": "Centre de Commandement",
    "admin.dashboard": "Tableau de Bord",
    "admin.localization": "Localisation & Tarification",
    "admin.pricing": "Gestion des Prix",
    "admin.users": "Utilisateurs",
    "admin.bookings": "Réservations",
    "admin.orders": "Commandes",
    "admin.settings": "Paramètres",
    "lang.select": "Langue",
    "currency.select": "Devise",
    "bismillah": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "common.person": "personne",
    "common.explore": "Explorer",
    "badge.limited": "Places Limitées",
    "badge.featured": "En Vedette",
    "home.hero.badge": "Approuvé par 50 000+ Pèlerins",
    "home.hero.title": "Votre Voyage Sacré",
    "home.hero.titleHighlight": "Commence Ici",
    "home.hero.searchPlaceholder": "Rechercher Hajj, Omra, Hôtels...",
    "home.services.badge": "Nos Services",
    "home.services.hajj": "Forfaits Hajj complets avec hébergement premium et guides experts.",
    "home.services.umrah": "Forfaits Omra spirituels adaptés à chaque pèlerin.",
    "home.services.hotels": "Hôtels premium près de la Mosquée Al-Haram et de la Mosquée du Prophète.",
    "home.services.flights": "Vols directs et avec escales vers Djeddah et Médine.",
    "home.services.visa": "Traitement de visa rapide et fiable pour tous les pèlerins.",
    "home.services.transport": "Transferts privés VIP et transport de groupe dans les Villes Saintes.",
    "home.services.tours": "Visites religieuses et culturelles guidées à La Mecque et Médine.",
    "home.services.store": "Essentiels premium pour votre voyage sacré.",
    "home.stats.pilgrims": "Pèlerins Satisfaits",
    "home.stats.years": "Ans d'Expérience",
    "home.stats.satisfaction": "Taux de Satisfaction",
    "home.stats.support": "Support Disponible",
    "home.hajj.badge": "Programmes Hajj",
    "home.hajj.title": "Forfaits Hajj en Vedette",
    "home.umrah.badge": "Programmes Omra",
    "home.umrah.title": "Forfaits Omra en Vedette",
    "home.why.badge": "Pourquoi Go Umrah",
    "home.why.title": "Votre Voyage, Notre",
    "home.why.titleHighlight": "Engagement",
    "home.why.subtitle": "Avec plus de 15 ans d'expérience, Go Umrah a guidé plus de 50 000 pèlerins dans leurs voyages sacrés.",
    "home.why.cta": "Commencez Votre Voyage",
    "home.testimonials.badge": "Témoignages",
    "home.testimonials.title": "Ce Que Disent Nos Pèlerins",
    "home.testimonials.t1": "Go Umrah a rendu notre expérience du Hajj vraiment inoubliable. L'attention aux détails, les conseils et le soutien tout au long du voyage étaient exceptionnels.",
    "home.testimonials.t2": "Nous avons voyagé en famille de 6 pour l'Omra et tout était parfaitement organisé. L'hôtel était à quelques pas du Haram.",
    "home.testimonials.t3": "Le traitement du visa était rapide et sans tracas. Les visites Ziyarat étaient incroyablement instructives et enrichissantes spirituellement.",
    "home.cta.title": "Prêt à Commencer Votre Voyage Sacré?",
    "home.cta.subtitle": "Rejoignez des milliers de pèlerins qui ont fait confiance à Go Umrah pour leurs expériences de Hajj et d'Omra.",
    "home.cta.hajjBtn": "Réserver un Forfait Hajj",
    "home.cta.umrahBtn": "Réserver un Forfait Omra",
    "home.features.licensed": "Agréé et Certifié par le Gouvernement",
    "home.features.multilingual": "Support Multilingue (6 Langues)",
    "home.features.transparent": "Tarification Transparente — Sans Frais Cachés",
    "home.features.payment": "Plans de Paiement Flexibles Disponibles",
    "home.features.realtime": "Confirmation de Réservation en Temps Réel",
    "home.features.insurance": "Assurance Voyage Complète Incluse",
    "common.hide": "Masquer",
    "common.view": "Voir",
    "visa.applyNow": "Postuler Maintenant",
    "visa.entry": "Entrée",
    "visa.processing": "Traitement",
    "visa.processingFee": "Frais de Traitement",
    "visa.requirements": "Conditions Requises",
    "visa.validity": "Validité",
    "footer.tagline": "Votre partenaire de confiance pour les voyages Hajj & Omra",
    "footer.quickLinks": "Liens Rapides",
    "footer.services": "Services",
    "footer.contact": "Contactez-nous",
    "footer.rights": "Tous droits réservés",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "common.allRatings": "Toutes les Notes",
    "common.allPrices": "Tous les Prix",
    "common.perRoom": "par chambre",
    "hotels.noResults": "Aucun hôtel trouvé",
    "hotels.mapView": "Vue Carte",
    "hotels.listView": "Vue Liste",
    "transport.private": "Privé",
    "transport.shared": "Partagé",
    "transport.pickup": "Lieu de Prise en Charge",
    "transport.dropoff": "Lieu de Dépose",
    "tours.duration": "Durée",
    "tours.groupSize": "Taille du Groupe",
    "tours.guide": "Guide",
    "tours.bookTour": "Réserver la Visite",
    "store.quantity": "Quantité",
    "store.total": "Total",
    "store.emptyCart": "Votre panier est vide",
    "store.continueShopping": "Continuer les Achats",
    "store.placeOrder": "Passer la Commande",
    "store.orderSuccess": "Commande passée avec succès!",
    "admin.add": "Ajouter Nouveau",
    "admin.edit": "Modifier",
    "admin.delete": "Supprimer",
    "admin.save": "Enregistrer les Modifications",
    "admin.cancel": "Annuler",
    "admin.hajj": "Programmes Hajj",
    "admin.umrah": "Programmes Omra",
    "admin.hotels": "Hôtels",
    "admin.flights": "Vols",
    "admin.visa": "Types de Visa",
    "admin.transport": "Transport",
    "admin.tours": "Visites",
    "admin.store": "Boutique",
    "admin.analytics": "Analytique",
    "common.internalPortal": "Portail Interne",
    "common.externalPortal": "Portail Externe",
    "hajj.nights": "Nuits",
    "hajj.includes": "Comprend",
    "hajj.economy": "Economique",
    "hajj.premium": "Premium",
    "hajj.vip": "VIP",
    "umrah.nights": "Nuits",
    "umrah.includes": "Comprend",
    "umrah.economy": "Economique",
    "umrah.premium": "Premium",
    "umrah.vip": "VIP",
  },
};

// ─── Context ──────────────────────────────────────────────────────────────────

interface LanguageContextValue {
  language: Language;
  languageConfig: LanguageConfig;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("go-umrah-lang");
    return (stored as Language) || "ar";
  });

  const languageConfig = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];
  const isRTL = languageConfig.dir === "rtl";

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("go-umrah-lang", lang);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
  }, [language, isRTL]);

  const t = useCallback((key: TranslationKey): string => {
    return translations[language][key] || translations["en"][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, languageConfig, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
